### ISSUE TITLE
Version goes backwards

### ISSUE THREAD

**Issue by eserte** [perlancar/perl-Bencher-Scenarios-LogGer#1]
According to https://metacpan.org/pod/Bencher::Scenarios::LogGer, the recent release (date 2021-06-10) has version 0.17, which is less than the older release from April 2021 (version 0.18).

(I noticed because CPAN.pm warns when trying to build+install the recent release:
```
Testing/Installation stopped: allow_installing_module_downgrades: PERLANCAR/Bencher-Scenarios-LogGer-0.017.tar.gz (called for P/PE/PERLANCAR/Bencher-Scenarios-LogGer-0.017.tar.gz) contains downgrading module(s) (e.g. Bencher/Scenarios/LogGer.pm'` would downgrade installed '0.018' to '0.017')
```
)

**Comment by perlancar** [comment]
Yup sorry, this was a screwup. I schedule my uploading of releases and I didn't make sure that version do not go backward. But I do now.
